[versions]
spotless = "8.0.0"
shadow = "9.2.2"
unimined = "8e64092954"

[libraries]
annotations = { group = "org.jetbrains", name = "annotations", version = "26.0.2" }
ignite-api = { group = "space.vectrix.ignite", name = "ignite-api", version = "1.1.0" }
mixin = { group = "org.spongepowered", name = "mixin", version = "0.8.5-SNAPSHOT" }
asm = { group = "org.ow2.asm", name = "asm-tree", version = "9.7.1"}

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
unimined = { id = "xyz.wagyourtail.unimined", version.ref = "unimined" }
